#!/bin/bash
#SBATCH -p gpu20
#SBATCH --gres gpu:2
#SBATCH -t 02-00:00:00
#SBATCH -o log/test_test_new.out

source activate
conda activate py36

# Run the training
srun python main.py

#conda deactivate
